
Option Explicit On
Option Infer Off
Option Strict On

'this file is generated by /osi/service/resource/zipgen/zipgen.exe with
'nlexer_rule syntaxer_rule
'so change /osi/service/resource/gen/gen.cs or resource files instead of this file

Imports System.IO
Imports System.IO.Compression
Imports osi.root.connector

Friend Module b2style_rules
    Public ReadOnly nlexer_rule() As Byte
    Public ReadOnly syntaxer_rule() As Byte

    Sub New()
        nlexer_rule = Convert.FromBase64String(strcat_hint(CUInt(604), _
        "H4sIAAAAAAAEAIVTwW7cIBS8I/EPL1s1lZJlV8oxsn1Je4hUtZf0VLcRa55jVBZcwOtU6p/10E/qLxSw8e7mkguaGR68NyP49+cvJfef7j5+ef8BNput67hFsdUKn9E+2kHhxj97Sij5MTLN9+h63iAsKOmN4s5BWhP3uO8V9wgZJNUc0Fop+E4hnODTvWUDY8c3cGf2PbfSGU2JQueYsQx/DlxBUVLyZDHcbY9iFcQJlQFp42f9opyP+45rKI4nE6+mXp97tNwbSwkXAuprSvZSDw5YAIPysle/oL6iRMhDHHQbZCPgLSW9GdHCd0p20jOuBVxO0Fiof4fbohKkRKMQ5oILShyqlkndhFaxWaICG2AsDtt65jrZeiiKOJyVT11WZIja6FbJxsMofbekDMVD8XBTVS8PVMlhajBZK2c2G1zo0WaWstmlJFrOZDae6WL/VEiuszBFkdkcSKZnnrN4bqOMPoQZwqthjVFGw+1tNLs6GCkChnYV04kBc6XCdGIN0oPrzKAE7HApbFdrML5DO0qHoeTdy0hTYazbUGL59PJZ3GFn7b/W4/rxW1xrEcBVHOeV73Qz/af/1fTFI3gDAAA="))

        assert(nlexer_rule.ungzip(nlexer_rule))
        syntaxer_rule = Convert.FromBase64String(strcat_hint(CUInt(1328), _
        "H4sIAAAAAAAEALUXu47bOLAXoH8YIF1gOcCVbq5Irghw2C3urhKMgJbGFhGaVEhqd52vz/Cph+WNN7hUFuf9nnFZfH74+Pd/n/6C7faD6ZjG9oO5SMteUH/Rg8CtfbFlURZaKVvZS49QH5jBKr83INkZTc8a+mwEM2YDFs+9YBb3npOfOluZjh8tnDQSWFe2Y3L2IDL2XDlJ1TO3XdUqCwkC9CiLd/DP0PdKW2Dbh93uAMdBNpYrCQ0TAphsCbHbOdTWUT/aDvUzNwjcgunUIFo4oDcW6lYNB4FVo4SS+z+hXiqfYN9fYy0BE6wsgsQ1mjeo2cDrStyXi3b1C/aPUspiIiMlaZQbjMjPkD08okbZIBy4rSjKDpgzDl+D6PDwco1l2lY90+ykWd+RbalSyBSU7Yhykt7BR6oEZIaLC/j6A6FOvAHnCOALN5bLEzSqRcpqSvnE1+RFUC7QmFBcTsvZaRUkYlFqWYyrnIWY11QE1w6aNV/RQv3ExICVk08pcJ5FTFnwk1SaegTNIGx1l7prXFn4bqq45JYzwb+jhjF9k1jfYdDhD2MvVBIGpXXJDJoMnnmoEqjnJnfI+spYPTQL8zdwt28bMCiOVTCKXBkMgXpiVT1q5pk8joDK2Gvolffk1GhxWdz25WfebsCPsFtoX/fe9mCT0lD7J2vb6NSZy8Gkb4oD78UlPlv+xNvk/Fkljl49o47fsZMmL5VQIziDBB7j+IyAyUDdR0OnQYYnpjlzAyDUyMwRT+j8OypNsW2oL4ijXsnU3QXxhpT6sE81hxFDQ8cTQP2KmlcrzQsO9juMGnJXkIZVeOoWLygbGiagx8wYRwqoB8n0ZcU3vgYnKav0UN8dNhKxQgu1VKkgKJqp+LDZpxzTwgxbz8S9uSYcorAVOaR2jWGSrVWmK7XrgUmKfU/Fdho7KTWR75/YOrlrUsP4h/vIU38zG/QRQeWG3wYmRuQIiT8UygDJwbth9MT5/8fwsbUnXf1bPJpPhVmnhd3vIeEzbv8lzUjiTjIIN8WdcwJuYuZ6bjO9beO5Qvz38dPjLp+NxGrpsEgKJrdQaPFGnc9ssmH9m/yTdEdyi62/YQzdTStsdNpk8Li3PSNzt1NYTAtRlBOuLeUoO+3OKfWEWvPWpWpia4TiGumULqjORPVSA9XdUtI4WveR38kOH5Nz8copt46Xt15M1UG1l7TAs/DF9Tfb5ZSMq2t0fozeedp5ek/gqyJmKwCu0+XhM6ZlJXhoKoUJZLypWxR4coYvz5CEmDma3XQhikHdwC0Zs9Tkm5Gyk7/HqCw9n/3Vmqktix+no5/t9g0AAA=="))

        assert(syntaxer_rule.ungzip(syntaxer_rule))
    End Sub
End Module
