
Option Explicit On
Option Infer Off
Option Strict On

'this file is generated by /osi/service/resource/zipgen/zipgen.exe with
'nlexer_rule syntaxer_rule
'so change /osi/service/resource/gen/gen.cs or resource files instead of this file

Imports System.IO
Imports System.IO.Compression
Imports osi.root.connector

Friend Module b2style_rules
    Public ReadOnly nlexer_rule() As Byte
    Public ReadOnly syntaxer_rule() As Byte

    Sub New()
        nlexer_rule = Convert.FromBase64String(strcat_hint(CUInt(536), _
        "H4sIAAAAAAAEAH2SsU7DMBCG93uKowiQoG4lRtR0KQxICCYmApUbX4iFYwfbaUDizRh4JF4Bx3EKXVis+y6/48/WfX9+wfXt6ub+8gpns7mruCUx14reyK5tq2jm3zzAS8c0r8k1vCDcVX27UNw5jGuPnupGcU84FgCHuDJ1w610RoMi55ixjF5brnCRwbOlkLK/vWUGQ5FloI1P3YNs2OorrnGx2xVx2Z9x15Dl3ljgQmB+BrXUrUMGdau8bNQ75qcg5FYKwjnURuARNKYji0+wkZ5xLfA4VsZi/gGRjyFCwCCCB+BIlUzqIvw/nBBJUIGMBbfSM1fJ0uNiAVY+VyMug11MDl7ZAMlupF/H1BlNx0Dvm+pknWjn/oejdOLhHgnSbRLtOafevnkGIEy7UcQKo4zGi4vw0JOtkSKUWE5QOuxfhisVpMQUpUdXmVYJ3NAuWE6maHxFtpOOQuQkjIvRpZKFx076agj2uRlYPgwa6z+wvcMf8m66fuzXXITiNMj8P7nncXR/AL0AXGfhAgAA"))

        assert(nlexer_rule.ungzip(nlexer_rule))
        syntaxer_rule = Convert.FromBase64String(strcat_hint(CUInt(1096), _
        "H4sIAAAAAAAEALVWO2/bMBDeBeg/HJCtMB2go5cOTYcCRTK0nQSjoKWzRYQSVZKK439fPkXJplO3aCeJ9/zuxWNZfH78+OX7wydYr+9VSyU29+rUa/qK8occOa71qy6LspBCaKJPA0K1owrJdF5BTztUA62RrKDmVKkVaOwGTjVunSo9EitDjky3pBEaIgXMoSzu4Os4DEJqoOvHzWYH+7GvNRM91JRzoH1jGJuNZa2t9JNuUR6ZQmAaVCtG3sAOHQyoGjHuOJJacNFvP0B17nzGfXfJ1YYYaWXhLeZk/sDNCt52Yv9sHslf4E9WymJmI2Y/2fUgpqMvC+5RYl8j7JgmJsuWmGoJz962O/nkKk2lJgOV9CDp0BpwsQkMFuybxLKmdu+VPhmwCntt3fgIFHbM44eKHXohTSuhGrkmLdKBKC3HWpPYAcR2wAoU8j15oXw0oXM6KhPPYBTFgJI6McczRKH0OdUkMfksi+tofod3Ba7xr7FdTh1QD0BIqNyRNk2IoGP9qOK/CZkN/BSODXthDUaeiBqDOKIM/6FKs5OIrESeSBz3mqiW7XUgSHZoA2UbgM4zCi9UMmqby5d6EYgTtPHthSSsryWaTITwlmW5uaQ31y+kfe55ulWcAFRvuHG6HqKtlxg12UlaP6NNQpYOVSInLH6AfEPNFZMEVGNP5SkDn+XoxkpWHqrbO7ssMrJQ9SLW3CQs9hfW21hGc9/6S1OFazdnHIKxjB3jNqcwK0hW6cJtPjHRsRubMDFpWOKcuBEJ0zENRpwJd7A/HJUiuqWmfAfTORplODmG6Sj8OVKemIkSPiaVnjIl7wroWfD/Bnia3tng/peIloO/GCa/OhzF/4blcS6TROxGB7+SbrwK4Cpn6ee60mw3nc0wZ0qb+9+upsCxN8cdfHt6eNpMrw6jqlk9vTrKwj1i7P7zP2mzXixA78b0N6ehHS6WRjS7mq2h83W52FBmlS/2t5XqXCjnm91znMdadB01ZjMCeXtJK6cDjpPVTOk4Z7sULZ8zU7vmnPiY5m0cXjGLiK8FOo8vH9ZlNImSXk4RmK339D/D/QZc/9oti18+n+y0RQsAAA=="))

        assert(syntaxer_rule.ungzip(syntaxer_rule))
    End Sub
End Module
