
Option Explicit On
Option Infer Off
Option Strict On

'this file is generated by /osi/service/resource/zipgen/zipgen.exe with
'nlexer_rule rlexer_rule syntaxer_rule
'so change /osi/service/resource/gen/gen.cs or resource files instead of this file

Imports System.IO
Imports System.IO.Compression
Imports osi.root.connector

Friend Module b2style_rules
    Public ReadOnly nlexer_rule() As Byte
    Public ReadOnly rlexer_rule() As Byte
    Public ReadOnly syntaxer_rule() As Byte

    Sub New()
        nlexer_rule = Convert.FromBase64String(strcat_hint(CUInt(744), _
        "H4sIAAAAAAAEAF1SwY7TMBC9R8o/DK1A0E3ae9nuHliQkBAnODVl5caT1KpjZ21nsyuWL+PAJ/ELzDhJW3HI5L3n8fh5xn9//0mTOXw7KA+V0gi90hr2CKU1j+gCSlAmWHDobedKzMBbmH/++uHL97uPIC16MDZAb91xyYU+Wa1tr0wNEitlVFDWeBCOC7aKqlXONrD34VnjqrQSazQro/EJ3b3rNC7DU6BCxz5XFagqItQegUNklXVAX8T9IVrmGLm0ZCkibW0LHCJzGDpnYPhFZe9QHCHGMb9WJcSYJmmy18IcYVvsd1eRWqthG1yHWSXIyC5NqCvk3cH2Kst3t9tCcmalrQgX0mI5LvjguCezbTHLFi+z3WLGZUvbNAKKjJG2BtZp8tCh557ljXBHuOWdwoW8FU7UTrQH+JkmaOSF8GvK2TtRHjHA2yFjou+mdf/Q0RxOerEd8v6X6W4eG5UPlt6zT+G9qk2DJsCG+RzuVFWhY4GH5lmkn8+ty5HqabimxJq6G9CdxRsSB7TZjBvCQRi4PudGfhMPlRIKal2jTOchJ9DpoFr9DMUiTaR6VBJhRbKV8DpNWtvTNH7QrFTIhZHwZoD0WooXqsYKSZGywK/2FV9VV7kyJR3Fh0UqsYQ8Zw+RDkY2IxvtnOjZ1CRN1k4pbHAio82JnsxeCtHjJAzGJzbaj1OgV2tEg74VJcIJ8QoTerx9dp+t1zsGhRwwde4flGcJmfIDAAA="))

        assert(nlexer_rule.ungzip(nlexer_rule))
        rlexer_rule = Convert.FromBase64String(strcat_hint(CUInt(436), _
        "H4sIAAAAAAAEAG2QTU7DMBCF95Z8h6EraGMOAP3ZUCQ2XMCJ0KSZpFYcu7UddYG4O3ZCoEAWfp5535PtMWdP++eX1z0Y7Ej0HktNkF+yvMreOOOsvQhVg6plfhUoxABIe4Ikc7C2DuKaQ5ejipcMOocrC5WdA9raEySZg45C7wyM21ygdIQtDPoPc1ZqNC3IvCxWsbFWgwyup6zGOF+REpq8F9YJOveoYb3hrIlnhR9rG62x2my+4uGIBtZTcui2nKH3qjEdmQAxeLBdh5ClQlsDD5yde/JBWSM6dC3sOPMBXRAndNg4PB3hPV5kqivjY8qUDg8tBbgdE1N7N3Ef3+fo28/lmPtjx3k9dUqML3pM0/vglGlgIRfFzXLBWa0tBpCrTBQ7mVfF6n5QzpQJ1JC7Rpyl74ZUi99fH9EnyJBYcYECAAA="))

        assert(rlexer_rule.ungzip(rlexer_rule))
        syntaxer_rule = Convert.FromBase64String(strcat_hint(CUInt(1052), _
        "H4sIAAAAAAAEAM1WzW7jIBC+W/I7oPa2CvsKPVWrvbSrtpeVZVXYJgkKBi/gRn37Hf5x7LQ99pKYb4b5+ZgZqKvfvx4en+5fX/7+uX9GHSfiVFdPj48vAdnPojdMih16I3ymeKB7JphF8JmZI9Z0ZLiX3GoIMlI9kZ7WVV3dogeJtFFzb5Cep0kq89Pi0aDT9j/aEGVwp0h/ogY1E1Fk5Eyb9g5RMSTBOHPDwKEwVPQUW7WDItOxrtKOsNmH1stxJO0P5KCgVEg8jtx3kOaYbKSfJbxiBGWZ3Z/oQKczzosi5ZQCar7OM2RkWSnS99EHQ5Gf3VW+2rqKYFZfn+ZCImdThpAtrEhpLuPPGfUcQighAGYNkSpqZiXSkh2EVBQHNDKDe8L5znLZKUpOO8TlgfU2Tr7HpT0om/IgPsgDNb0UQ4jyfGQcnO+lwlzKqbW8XqNwfX5RZ+t0VvmXdbYqotwXRGugYgTLnq+o7NO8prPiwys2DifDEBgbmZh1/LZpTvw9LAf2xgYaZTLumOSZqvDdMYOJGIqVjKIMS9XGoOoqMW1PkO0vmt6pLbq94JZyDbnE/e1dXS0Ra9EiaMG6O08r8h9f9ueGVCgCux2+LyfU1YLOx7gowrBjC8s1ezUYH2tQd+0W1KLXWNgBbmOdlLqf5V9XipxxcHXRcm9EMdJx6oYYtCdU+sFWwp5LAkF0UoISjHomDgvfRUyoSebLqLGcqGdwGXSCUTMLot4zEG10bAsHK5v6cC/AQFkZmaQ2GyY2dFEjpAllzUScOlABqcJv0TMkzId42W0aD7w3G3bA7daG4lQ2N63cbhMTHbv+D62fuz42vOv10Oapw2Nzu4X94FRrbI4Eqv4Ak9hQFVZOAJ1D/82EZ2FG3F9i7EqkRcbfKVpbn0UbpFfCB5cVWqzKx48Xbz1+fBOsXz+xPfwrp2iV+MpZ3BDFK8dTGV450OXlVWvHmwfShPJPt/uxowMi/oq1IRrqrpiBKdobewicnWgQ38BAAJ0B2h2RVz8HburKC8FDNGLxuvoP0+ACxHIKAAA="))

        assert(syntaxer_rule.ungzip(syntaxer_rule))
    End Sub
End Module
