' This file is created by genall with
' C:\Users\hzj_jie\git\osi.net\service\resource\gen\gen.exe
' _b3style_test_data "[__func__]" "__func__.txt"

Option Explicit On
Option Infer Off
Option Strict On

'this file is generated by /osi/service/resource/gen/gen.exe with
'[__func__]
'so change /osi/service/resource/gen/gen.cs or resource files instead of this file

Imports osi.root.connector

Friend Module _b3style_test_data
    Public ReadOnly [__func__]() As Byte

    Sub New()
        [__func__] = Convert.FromBase64String(strcat_hint(CUInt(532), _
        "77u/DQojaW5jbHVkZSA8YjJzdHlsZS5oPg0KI2luY2x1ZGUgPGIyc3R5bGUvc3RkaW8uaD4NCg0KbmFtZXNwYWNlIE4gew0KICA6OnZvaWQgcHJpbnQoKSB7DQogICAgOjpiMnN0eWxlOjpzdGRfb3V0KF9fZnVuY19fKTsNCiAgICA6OmIyc3R5bGU6OnN0ZF9vdXQoIlxuIik7DQogIH0NCg0KICA6OnZvaWQgZjIoOjppbnQgeCwgOjpzdHJpbmcgcykgew0KICAgIDo6YjJzdHlsZTo6c3RkX291dChfX2Z1bmNfXyk7DQogICAgOjpiMnN0eWxlOjpzdGRfb3V0KCJcbiIpOw0KICB9DQp9ICAvLyBuYW1lc3BhY2UgTg0KDQp2b2lkIG1haW4oKSB7DQogIGIyc3R5bGU6OnN0ZF9vdXQoX19mdW5jX18pOw0KICBiMnN0eWxlOjpzdGRfb3V0KCJcbiIpOw0KICBOOjpwcmludCgpOw0KICBOOjpmMigxLCAiIik7DQp9"))
    End Sub
End Module
