Option Explicit On
Option Infer Off
Option Strict On
Imports osi.root.connector
Public NotInheritable Class b3style_runnable_test_cases
    Private Sub New()
    End Sub
    Public Shared ReadOnly data() As Byte = 
        Convert.FromBase64String(strcat_hint(CUInt(847), 
            "EAAAAGJzdHlsZS1jYXNlMS50eHSNAAAA77u/CiNpbmNsdWRlIDxic3R5bGUuaD4KCnZvaWQgcHJpbnQoc3RyaW5nIGkpIHsKICBzdHJpbmcgdGVtcDsKICBsb2dpYyAiaW50ZXJydXB0IHN0ZG91dCBpIHRlbXAiOwp9Cgp2b2lkIG1haW4oKSB7CiAgcHJpbnQoIkhlbGxvIFdvcmxkIik7Cn0KDgAAAGVtcHR5LW1haW4udHh0EwAAAO+7vwp0eXBlMCBtYWluKCkge30RAAAAZnVuY3Rpb24tY2FsbC50eHSoAAAA77u/CiNpbmNsdWRlIDxic3R5bGUvdHlwZXMuaD4KCnN0cmluZyBmKHN0cmluZyB4KSB7CiAgcmV0dXJuIHg7Cn0KCnZvaWQgbWFpbigpIHsKICBzdHJpbmcgaSA9ICJIZWxsbyBXb3JsZCI7CiAgc3RyaW5nIHRlbXAgPSBmKGkpOwogIGxvZ2ljICJpbnRlcnJ1cHQgc3Rkb3V0IHRlbXAgaSI7Cn0KDwAAAGhlbGxvLXdvcmxkLnR4dH0AAADvu78KI2luY2x1ZGUgPGJzdHlsZS90eXBlcy5oPgoKdm9pZCBtYWluKCkgewogIHN0cmluZyBpID0gIkhlbGxvIFdvcmxkIjsKICBzdHJpbmcgdGVtcDsKICBsb2dpYyAiaW50ZXJydXB0IHN0ZG91dCBpIHRlbXAiOwp9ChgAAABpbmNsdWRlLWJzdHlsZS10eXBlcy50eHRvAAAA77u/CiNpbmNsdWRlIDxic3R5bGUvdHlwZXMuaD4KLy8gSW5jbHVkZSBpdCB0d2ljZSB0byB0ZXN0IHRoZSBpZm5kZWYuCiNpbmNsdWRlIDxic3R5bGUvdHlwZXMuaD4KCnZvaWQgbWFpbigpIHt9FQAAAHByZWRlZmluZWQtbWFjcm9zLnR4dIAAAADvu78KI2luY2x1ZGUgPGJzdHlsZS90eXBlcy5oPgoKdm9pZCBtYWluKCkgewogIHN0cmluZyBpID0gX19mdW5jX187CiAgaSA9IF9fRklMRV9fOwogIGkgPSBfX1NUQVRFTUVOVF9fOwoKICBpbnQgaiA9IF9fTElORV9fOwp9Cg=="
        ))
End Class
