Option Explicit On
Option Infer Off
Option Strict On
Imports osi.root.connector
Public NotInheritable Class b3style_runnable_test_cases
    Private Sub New()
    End Sub
    Public Shared ReadOnly data() As Byte = 
        Convert.FromBase64String(strcat_hint(CUInt(713), 
            "EQAAAGZ1bmN0aW9uLWNhbGwudHh0tAAAAO+7vw0KI2luY2x1ZGUgPGJzdHlsZS90eXBlcy5oPg0KDQpzdHJpbmcgZihzdHJpbmcgeCkgew0KICByZXR1cm4geDsNCn0NCg0Kdm9pZCBtYWluKCkgew0KICBzdHJpbmcgaSA9ICJIZWxsbyBXb3JsZCI7DQogIHN0cmluZyB0ZW1wID0gZihpKTsNCiAgbG9naWMgImludGVycnVwdCBzdGRvdXQgdGVtcCBpIjsNCn0NCg8AAABoZWxsby13b3JsZC50eHSFAAAA77u/DQojaW5jbHVkZSA8YnN0eWxlL3R5cGVzLmg+DQoNCnZvaWQgbWFpbigpIHsNCiAgc3RyaW5nIGkgPSAiSGVsbG8gV29ybGQiOw0KICBzdHJpbmcgdGVtcDsNCiAgbG9naWMgImludGVycnVwdCBzdGRvdXQgaSB0ZW1wIjsNCn0NChgAAABpbmNsdWRlLWJzdHlsZS10eXBlcy50eHR0AAAA77u/DQojaW5jbHVkZSA8YnN0eWxlL3R5cGVzLmg+DQovLyBJbmNsdWRlIGl0IHR3aWNlIHRvIHRlc3QgdGhlIGlmbmRlZi4NCiNpbmNsdWRlIDxic3R5bGUvdHlwZXMuaD4NCg0Kdm9pZCBtYWluKCkge30VAAAAcHJlZGVmaW5lZC1tYWNyb3MudHh0igAAAO+7vw0KI2luY2x1ZGUgPGJzdHlsZS90eXBlcy5oPg0KDQp2b2lkIG1haW4oKSB7DQogIHN0cmluZyBpID0gX19mdW5jX187DQogIGkgPSBfX0ZJTEVfXzsNCiAgaSA9IF9fU1RBVEVNRU5UX187DQoNCiAgaW50IGogPSBfX0xJTkVfXzsNCn0NCgkAAABjYXNlMS50eHQUAAAA77u/DQp0eXBlMCBtYWluKCkge30="
        ))
End Class
