<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>osi.service.xml</RootNamespace>
    <AssemblyName>osi.service.xml</AssemblyName>
    <OptionExplicit>On</OptionExplicit>
    <OptionCompare>Binary</OptionCompare>
    <OptionStrict>Off</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System" />
  </ItemGroup>

  <Import Project="xml.net8.dep" />
</Project>
