<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>osi.tests.service.commander</RootNamespace>
    <AssemblyName>osi.tests.service.commander</AssemblyName>
    <OptionExplicit>On</OptionExplicit>
    <OptionCompare>Binary</OptionCompare>
    <OptionStrict>Off</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System" />
    <Compile Remove="My Project\**" />
  </ItemGroup>

  <Import Project="..\..\..\root\root.utt.net8.props" />
  <Import Project="$(ServicePath)\commander\commander.net8.props" />
  <Import Project="$(ServicePath)\convertor\convertor.net8.props" />
  <Import Project="$(ServicePath)\tcp\tcp.net8.props" />
  <Import Project="$(ServicePath)\udp\udp.net8.props" />
  <Import Project="$(ServicePath)\http\http.net8.props" />

  <ItemGroup>
    <ProjectReference Include="$(ServicePath)\tests\transmitter\transmitter.net8.vbproj" />
  </ItemGroup>
</Project>
