
Option Explicit On
Option Infer Off
Option Strict On

'this file is generated by /osi/service/resource/gen/gen.exe with
'case1 case2 bool_and_bool str_unescape _1_to_100 self_add biguint negative_int another_1_to_100 loaded_method ufloat_std_out ufloat_operators while_1_to_100 while_0_to_1 pi_integral_0_1 calculate_pi_bbp shift order_of_operators
'so change /osi/service/resource/gen/gen.cs or resource files instead of this file

Imports osi.root.connector

Friend Module _b2style_test_data
    Public ReadOnly case1() As Byte
    Public ReadOnly case2() As Byte
    Public ReadOnly bool_and_bool() As Byte
    Public ReadOnly str_unescape() As Byte
    Public ReadOnly _1_to_100() As Byte
    Public ReadOnly self_add() As Byte
    Public ReadOnly biguint() As Byte
    Public ReadOnly negative_int() As Byte
    Public ReadOnly another_1_to_100() As Byte
    Public ReadOnly loaded_method() As Byte
    Public ReadOnly ufloat_std_out() As Byte
    Public ReadOnly ufloat_operators() As Byte
    Public ReadOnly while_1_to_100() As Byte
    Public ReadOnly while_0_to_1() As Byte
    Public ReadOnly pi_integral_0_1() As Byte
    Public ReadOnly calculate_pi_bbp() As Byte
    Public ReadOnly shift() As Byte
    Public ReadOnly order_of_operators() As Byte

    Sub New()
        case1 = Convert.FromBase64String(strcat_hint(CUInt(76), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIGIyc3R5bGU6OnN0ZF9vdXQoIkhlbGxvIFdvcmxkIik7DQp9"))
        case2 = Convert.FromBase64String(strcat_hint(CUInt(416), _
        "77u/DQpib29sIGlzX2V2ZW4obG9uZyBpKSB7DQogIGxvbmcgXzIgPSAyOw0KICBsb25nIF8wID0gMDsNCiAgcmV0dXJuIGIyc3R5bGU6OmVxdWFsKGIyc3R5bGU6Om1vZChpLCBfMiksIF8wKTsNCn0NCg0Kdm9pZCBtYWluKCkgew0KICBmb3IgKGludCBpID0gMDsgaSA8IDEwMDsgaSA9IGkrKykgew0KICAgIGxvbmcgeDsNCiAgICB4ID0gYjJzdHlsZTo6Y3VycmVudF9tcygpOw0KICAgIGlmIChpc19ldmVuKHgpKSB7DQogICAgICB4ID0geC0tOw0KICAgIH0NCiAgICBiMnN0eWxlOjpib29sX3N0ZF9vdXQoaXNfZXZlbih4KSk7DQogIH0NCn0NCg=="))
        bool_and_bool = Convert.FromBase64String(strcat_hint(CUInt(468), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIGIyc3R5bGU6OmJvb2xfc3RkX291dCh0cnVlICYmIHRydWUpOw0KICBiMnN0eWxlOjpib29sX3N0ZF9vdXQodHJ1ZSAmJiBmYWxzZSk7DQogIGIyc3R5bGU6OmJvb2xfc3RkX291dChmYWxzZSAmJiB0cnVlKTsNCiAgYjJzdHlsZTo6Ym9vbF9zdGRfb3V0KGZhbHNlICYmIGZhbHNlKTsNCiAgYjJzdHlsZTo6Ym9vbF9zdGRfb3V0KHRydWUgfHwgdHJ1ZSk7DQogIGIyc3R5bGU6OmJvb2xfc3RkX291dCh0cnVlIHx8IGZhbHNlKTsNCiAgYjJzdHlsZTo6Ym9vbF9zdGRfb3V0KGZhbHNlIHx8IHRydWUpOw0KICBiMnN0eWxlOjpib29sX3N0ZF9vdXQoZmFsc2UgfHwgZmFsc2UpOw0KfQ0K"))
        str_unescape = Convert.FromBase64String(strcat_hint(CUInt(76), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIGIyc3R5bGU6OnN0ZF9vdXQoImFiY1x0ZGVmXG4iKTsNCn0="))
        _1_to_100 = Convert.FromBase64String(strcat_hint(CUInt(208), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIGludCB4ID0gMDsNCiAgZm9yIChpbnQgaSA9IDA7IGkgPCAxMDA7IGkgPSBpKyspIHsNCiAgICB4ID0geCArIGkgKyAxOw0KICB9DQogIGIyc3R5bGU6OmludF9zdGRfb3V0KHgpOw0KICBiMnN0eWxlOjpzdGRfb3V0KCJcbiIpOw0KfQ=="))
        self_add = Convert.FromBase64String(strcat_hint(CUInt(104), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIGludCBpID0gMTAwOw0KICBpICs9IDE7DQogIGIyc3R5bGU6OmludF9zdGRfb3V0KGkpOw0KfQ=="))
        biguint = Convert.FromBase64String(strcat_hint(CUInt(256), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIGJpZ3VpbnQgaSA9IDQyOTQ5NjcyOTZMOw0KICBiaWd1aW50IGogPSA0Mjk0OTY3Mjk2bDsNCiAgYmlndWludCBrID0gMUw7DQogIGIyc3R5bGU6OmJpZ3VpbnRfc3RkX291dChpKTsNCiAgYjJzdHlsZTo6YmlndWludF9zdGRfb3V0KGopOw0KICBiMnN0eWxlOjpiaWd1aW50X3N0ZF9vdXQoayk7DQp9"))
        negative_int = Convert.FromBase64String(strcat_hint(CUInt(144), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIGIyc3R5bGU6OmludF9zdGRfb3V0KC0xKTsNCiAgYjJzdHlsZTo6aW50X3N0ZF9vdXQoLTIpOw0KICBiMnN0eWxlOjppbnRfc3RkX291dCgtMyk7DQp9"))
        another_1_to_100 = Convert.FromBase64String(strcat_hint(CUInt(196), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIGludCB4ID0gMDsNCiAgZm9yIChpbnQgaSA9IDE7IGkgPD0gMTAwOyBpICs9IDEpIHsNCiAgICB4ICs9IGk7DQogIH0NCiAgYjJzdHlsZTo6aW50X3N0ZF9vdXQoeCk7DQogIGIyc3R5bGU6OnN0ZF9vdXQoIlxuIik7DQp9"))
        loaded_method = Convert.FromBase64String(strcat_hint(CUInt(772), _
        "77u/DQpsb25nIGxvYWRlZF9jdXJyZW50X21zKCkgew0KICBzdHJpbmcgbWV0aG9kX25hbWUgPSBiMnN0eWxlOjpsb2FkZWRfbWV0aG9kcygiY3VycmVudF9tcyIpOw0KICBsb2dpYyAiaW50ZXJydXB0IGxvYWRfbWV0aG9kIG1ldGhvZF9uYW1lIEBAcHJlZml4ZXNAdGVtcHNAc3RyaW5nIjsNCiAgbG9uZyByZXN1bHQ7DQogIGxvZ2ljICJpbnRlcnJ1cHQgZXhlY3V0ZV9sb2FkZWRfbWV0aG9kIEBAcHJlZml4ZXNAdGVtcHNAc3RyaW5nIHJlc3VsdCI7DQogIHJldHVybiByZXN1bHQ7DQp9DQoNCmJvb2wgaXNfZXZlbihsb25nIGkpIHsNCiAgbG9uZyBfMiA9IDI7DQogIGxvbmcgXzAgPSAwOw0KICByZXR1cm4gYjJzdHlsZTo6ZXF1YWwoYjJzdHlsZTo6bW9kKGksIF8yKSwgXzApOw0KfQ0KDQp2b2lkIG1haW4oKSB7DQogIGZvciAoaW50IGkgPSAwOyBpIDwgMTAwOyBpID0gaSsrKSB7DQogICAgbG9uZyB4Ow0KICAgIHggPSBsb2FkZWRfY3VycmVudF9tcygpOw0KICAgIGlmIChpc19ldmVuKHgpKSB7DQoJICB4ID0geC0tOw0KCX0NCiAgICBiMnN0eWxlOjpib29sX3N0ZF9vdXQoaXNfZXZlbih4KSk7DQogIH0NCn0gDQo="))
        ufloat_std_out = Convert.FromBase64String(strcat_hint(CUInt(88), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIHVmbG9hdCBmID0gMS4xOw0KICBiMnN0eWxlOjpzdGRfb3V0KGYpOw0KfQ=="))
        ufloat_operators = Convert.FromBase64String(strcat_hint(CUInt(224), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIHVmbG9hdCBpID0gMi4yOw0KICBpICs9IDMuMDsNCiAgaSAtPSAzLjA7DQogIGkgLz0gMi4wOw0KICBiMnN0eWxlOjpzdGRfb3V0KGkpOw0KICBpID0gYjJzdHlsZTo6dWZsb2F0OjpmcmFjdGlvbigxLCAyKTsNCiAgYjJzdHlsZTo6c3RkX291dChpKTsNCn0="))
        while_1_to_100 = Convert.FromBase64String(strcat_hint(CUInt(204), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIGludCB4ID0gMDsNCiAgaW50IGkgPSAwOw0KICB3aGlsZSAoaSA8IDEwMCkgew0KICAgIGkgKz0gMTsNCgl4ICs9IGk7DQogIH0NCiAgYjJzdHlsZTo6aW50X3N0ZF9vdXQoeCk7DQogIGIyc3R5bGU6OnN0ZF9vdXQoIlxuIik7DQp9"))
        while_0_to_1 = Convert.FromBase64String(strcat_hint(CUInt(220), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIHVmbG9hdCB4ID0gMC4wOw0KICB1ZmxvYXQgaSA9IDAuMDsNCiAgd2hpbGUgKGkgPCAxLjApIHsNCiAgICBpICs9IDAuMDE7DQoJeCArPSBpOw0KICB9DQogIGIyc3R5bGU6OnN0ZF9vdXQoeCk7DQogIGIyc3R5bGU6OnN0ZF9vdXQoIlxuIik7DQp9DQo="))
        pi_integral_0_1 = Convert.FromBase64String(strcat_hint(CUInt(288), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIHVmbG9hdCBkeCA9IDAuMTsNCiAgdWZsb2F0IHggPSAwLjA7DQogIHVmbG9hdCBzID0gMC4wOw0KICB3aGlsZSAoeCA8IDEuMCkgew0KICAgIHVmbG9hdCBjID0gMS4wIC0gKHggXiAyLjApOw0KCWMgXj0gMC41Ow0KCWMgKj0gZHg7DQoJcyArPSBjOw0KCXggKz0gZHg7DQogIH0NCg0KICBiMnN0eWxlOjpzdGRfb3V0KHMgKiA0LjApOw0KfQ=="))
        calculate_pi_bbp = Convert.FromBase64String(strcat_hint(CUInt(528), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIHVmbG9hdCBzID0gMC4wOw0KICBmb3IgKGludCBpID0gMDsgaSA8IDU1OyBpID0gaSsrKSB7DQogICAgdWZsb2F0IGMgPSBiMnN0eWxlOjp1ZmxvYXQ6OmZyYWN0aW9uKDQsIDEgKyAoOCAqIGkpKTsNCgljIC09IGIyc3R5bGU6OnVmbG9hdDo6ZnJhY3Rpb24oMiwgNCArICg4ICogaSkpOw0KCWMgLT0gYjJzdHlsZTo6dWZsb2F0OjpmcmFjdGlvbigxLCA1ICsgKDggKiBpKSk7DQoJYyAtPSBiMnN0eWxlOjp1ZmxvYXQ6OmZyYWN0aW9uKDEsIDYgKyAoOCAqIGkpKTsNCgliaWd1aW50IGIgPSAxOw0KCWMgKj0gYjJzdHlsZTo6dWZsb2F0OjpmcmFjdGlvbigxLCBiIDw8ICg0ICogaSkpOw0KCXMgKz0gYzsNCiAgfQ0KICBiMnN0eWxlOjpzdGRfb3V0KHMpOw0KfQ0K"))
        shift = Convert.FromBase64String(strcat_hint(CUInt(200), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIGludCBpID0gMTAwOw0KICBpIDw8PSAyOw0KICBiMnN0eWxlOjpzdGRfb3V0KGkpOw0KICBpbnQgaiA9IDA7DQogIGogPSBpID4+IDU7DQogIGIyc3R5bGU6OnN0ZF9vdXQoaSk7DQogIGIyc3R5bGU6OnN0ZF9vdXQoaik7DQp9"))
        order_of_operators = Convert.FromBase64String(strcat_hint(CUInt(128), _
        "77u/DQp2b2lkIG1haW4oKSB7DQogIGIyc3R5bGU6OnN0ZF9vdXQoMSArIDIgKiAzICsgNCAtIDUgKiA2ICogNyAqIDggKiA5IC8gMTAgKiAoMTEgKyAxMikpOw0KfQ=="))
    End Sub
End Module
