
'this file is generated by /osi/root/codegen/tfver.cmd
'so change the script instead of this file

Public Module _tfver
    Public ReadOnly tf_latest_changeset As String = _
         "".Trim()
    Public ReadOnly tf_current_changeset As String = _
         "".Trim()
End Module
