
Option Explicit On
Option Infer Off
Option Strict On

'this file is generated by /osi/service/resource/zipgen/zipgen.exe with
'nlexer_rule syntaxer_rule
'so change /osi/service/resource/gen/gen.cs or resource files instead of this file

Imports System.IO
Imports System.IO.Compression
Imports osi.root.connector

Friend Module b3style_rules
    Public ReadOnly nlexer_rule() As Byte
    Public ReadOnly syntaxer_rule() As Byte

    Sub New()
        nlexer_rule = Convert.FromBase64String(strcat_hint(CUInt(80), _
        "H4sIAAAAAAAEAHu/ez+Xp5+zT6iLq4Kenn6SUXFJZU6qfl5OakVqUXxRaU6qXklFCRcXAAmZr8soAAAA"))

        assert(nlexer_rule.ungzip(nlexer_rule))
        syntaxer_rule = Convert.FromBase64String(strcat_hint(CUInt(80), _
        "H4sIAAAAAAAEAOPy9HP2CXVxVdDT008yKi6pzEnVL67MK0msSC2KLyrNSdUrqSjh4gIAWgSQ3CcAAAA="))

        assert(syntaxer_rule.ungzip(syntaxer_rule))
    End Sub
End Module
