
Option Explicit On
Option Infer Off
Option Strict On

'this file is generated by /osi/service/resource/zipgen/zipgen.exe with
'nlexer_rule rlexer_rule syntaxer_rule
'so change /osi/service/resource/gen/gen.cs or resource files instead of this file

Imports System.IO
Imports System.IO.Compression
Imports osi.root.connector

Friend Module cstyle_rules
    Public ReadOnly nlexer_rule() As Byte
    Public ReadOnly rlexer_rule() As Byte
    Public ReadOnly syntaxer_rule() As Byte

    Sub New()
        nlexer_rule = Convert.FromBase64String(strcat_hint(CUInt(508), _
        "H4sIAAAAAAAEAF1SUU7DMAz9j5Q7mEkg6Br4h20cpC0oI24XNU26JGVCwMn44EhcASfdAPFR973nV9tx+vXxyVl/ELoF3WaEJiCkkFnrPNCT8WGnDUKOmSsHymVknBshhcw8xslbmF9Z2XqUPeTIGWdbI20PVb1tlpk6Z6CKfsKyldS44UzbiB16qJalaO6rWiVna5yMf6Ti+pgI0WvbwaKqF2XxtmiKRSr75IZBQl0mZJyFW872E4aonRWD9D3cpy+lj2KUXnZejjt45Qyt+iO8nzxbL596jHA5O0706pQP+0l6/NHravb9l+lsAQct5pHu0pwGQxDOCySrgdWas44WFX+lDUkzWq+P9riTFlYnZ2abVEuGoDs7oI2wzlwpqGlDg7ZTAEFgMlGP5gXqgjOln7VCuCHZKTjnbHQHWvoDXYmOQloFFzOkn+CNiiWBlMSIWhfhLB3HtCL1WS6P5NhMpAGsHJBu+lA+NinWikCREt/RjiO2eQIAAA=="))

        assert(nlexer_rule.ungzip(nlexer_rule))
        rlexer_rule = Convert.FromBase64String(strcat_hint(CUInt(436), _
        "H4sIAAAAAAAEAG2QTU7DMBCF95Z8h6EraGMOAP3ZUCQ2XMCJ0KSZpFYcu7UddYG4O3ZCoEAWfp5535PtMWdP++eX1z0Y7Ej0HktNkF+yvMreOOOsvQhVg6plfhUoxABIe4Ikc7C2DuKaQ5ejipcMOocrC5WdA9raEySZg45C7wyM21ygdIQtDPoPc1ZqNC3IvCxWsbFWgwyup6zGOF+REpq8F9YJOveoYb3hrIlnhR9rG62x2my+4uGIBtZTcui2nKH3qjEdmQAxeLBdh5ClQlsDD5yde/JBWSM6dC3sOPMBXRAndNg4PB3hPV5kqivjY8qUDg8tBbgdE1N7N3Ef3+fo28/lmPtjx3k9dUqML3pM0/vglGlgIRfFzXLBWa0tBpCrTBQ7mVfF6n5QzpQJ1JC7Rpyl74ZUi99fH9EnyJBYcYECAAA="))

        assert(rlexer_rule.ungzip(rlexer_rule))
        syntaxer_rule = Convert.FromBase64String(strcat_hint(CUInt(960), _
        "H4sIAAAAAAAEAI1VS27bMBDdC9AdBuimLSzfIAi6CIpukiLNphCEgpYomzXFUUkqrm/foUjK1CdINzb1OP83M8yzb18fn54ffr38/P7wAw6SqXOePT89vQSkHVRtBao8y7MP8IhgrB5qC2boe9R27/AoA4p13P8Yy7QtDprVZ26h7JlmnRTGVvfAVTNddIO0ojBcWa5qXjixo2b9Kc8mjaBcXIQ9FTV2Has+wwgFoeTG4zCew+0tJhfp5ADK6HT3ZhBVnkXwJu69Gd4JcilR7WB2g4NdXMZzYm1pA8pXJgdeNLwVSrhK7iAitaRwUoiAwVDUmttBq+kzclDUTModnC9UY87OVRLBIoB5qFDWqJrg/HIS0tlEXUjEvnKle6tKgeqNyhJPjuuE1DxbpZXys6xC0k/MGHFUHVn2ZfDNaJeJw52/BmHg90DNw8BclWV/qV+PTAO2sW5CUdwuEWyLmYk99pxCQ333cTT1iUhEaBAUWufVUlktCJqAnteiFU7nCkKBPXGoC2OvkoPkr1zu4YuZkAa5cSaAxPEC0T2wEdnH5D2db+WcZxNJjmHRLubM554OWEILl4bsR/3qPs/miLPoEJgRNraCu/KH//Y37oXQP06dzsulsOoFWg6rodjCQpUWu2TdZ1F8HLcgFscoTkCAq0hAKvtetqlOYgtKR99qJGkruRBNMsujM99vIypocI5ck6pERqEeEEmRNq5Qx3mEkxKUg2L6egOKUYp0xRZOVjblactqvjbSo7EbJjZkKWm0bt/JlmarDicit4rNu2Ur1LTcUMuz7QyiCmsaWt1CDSZs8F5ed9CIV9G4nY6Ni/7iinkQtmCq8QckYPxAPUWWMBOtS25MYU+MSDm6gQ/nEaau5n8GJuPV7Xv8q27TOt9NWw+jp3T9Mkay/QuYEB9fwOBjeRPiDy9gns1eCTeHHpiGK8/+ARCUnWUCCAAA"))

        assert(syntaxer_rule.ungzip(syntaxer_rule))
    End Sub
End Module
