
Option Explicit On
Option Infer Off
Option Strict On

'this file is generated by /osi/service/resource/gen/gen.exe with
'from_source1
'so change /osi/service/resource/gen/gen.cs or resource files instead of this file

Imports osi.root.connector

Friend Module _dotnet_test_data
    Public ReadOnly from_source1() As Byte

    Sub New()
        from_source1 = Convert.FromBase64String(strcat_hint(CUInt(216), _
        "CnB1YmxpYyBjbGFzcyBmcm9tX3NvdXJjZTEgewogICAgcHVibGljIHN0YXRpYyBpbnQgZXhlY3V0ZShpbnQgYSkgewogICAgICAgIHJldHVybiBhICsgMTsKICAgIH0KCiAgICBwdWJsaWMgaW50IGV4ZWN1dGUyKGludCBhKSB7CiAgICAgICAgcmV0dXJuIGEgLSAxOwogICAgfQp9Cg=="))
    End Sub
End Module
