
Option Explicit On
Option Infer Off
Option Strict On

'the following code is generated by /osi/root/codegen/precompile/precompile.exe
'with disposer.vbp ----------
'so change disposer.vbp instead of this file




'the following code is generated by /osi/root/codegen/precompile/precompile.exe
'with disposer_imports.vbp ----------
'so change disposer_imports.vbp instead of this file


Imports osi.root.connector
Imports osi.root.lock
'finish disposer_imports.vbp --------

Public Class disposer
    Implements IDisposable

    Private ReadOnly _disposer As Action

    Public Sub New(Optional ByVal disposer As Action = Nothing)
        _disposer = disposer
    End Sub

    Protected Overridable Sub disposer()
        assert(Not _disposer Is Nothing)
        _disposer()
    End Sub

    Private Sub do_dispose()
        disposer()
    End Sub


'the following code is generated by /osi/root/codegen/precompile/precompile.exe
'with disposer_core.vbp ----------
'so change disposer_core.vbp instead of this file



    <Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly")>
    Public Event dispose_exception(ByVal ex As Exception)
    Private exp As singleentry

    Private sub mark_and_dispose()
        If exp.mark_in_use() Then
            Try
                do_dispose()
            Catch ex As Exception
                If event_attached(dispose_exceptionEvent) Then
                    RaiseEvent dispose_exception(ex)
                Else
                    log_unhandled_exception(ex)
                End If
            End Try
        End If
        GC.KeepAlive(Me)
    End Sub

    Public Function disposed() As Boolean
        Return exp.in_use()
    End Function

    Public Sub dispose()
        mark_and_dispose()
#If True Then
        GC.SuppressFinalize(Me)
#End If
    End Sub


'the following code is generated by /osi/root/codegen/precompile/precompile.exe
'with disposer_dispose.vbp ----------
'so change disposer_dispose.vbp instead of this file



#If True Then
    <Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1063:ImplementIDisposableCorrectly")>
    Public Sub IDisposable_Dispose() Implements IDisposable.Dispose
        dispose()
    End Sub
#End If

#If True Then
    <Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1063:ImplementIDisposableCorrectly")>
    Protected NotOverridable Overrides Sub Finalize()
        dispose()
        GC.KeepAlive(Me)
        MyBase.Finalize()
    End Sub
#End If
'finish disposer_dispose.vbp --------
'finish disposer_core.vbp --------
End Class
'finish disposer.vbp --------
