
' This file is generated by commands-parser, with commands.txt file.
' So change commands-parser or commands.txt instead of this file.

Imports osi.service.interpreter.primitive
Imports osi.service.interpreter.primitive.instructions

Namespace primitive
    Namespace instructions
        Public Class push_exportable_test
            Inherits exportable_test(Of [push])

            Protected Overrides Function create() As [push]
                Return New [push]()
            End Function
        End Class

        Public Class pop_exportable_test
            Inherits exportable_test(Of [pop])

            Protected Overrides Function create() As [pop]
                Return New [pop]()
            End Function
        End Class

        Public Class pushm_exportable_test
            Inherits exportable_test(Of [pushm])

            Protected Overrides Function create() As [pushm]
                Return New [pushm]( _
                        data_ref.random())
            End Function
        End Class

        Public Class popm_exportable_test
            Inherits exportable_test(Of [popm])

            Protected Overrides Function create() As [popm]
                Return New [popm]( _
                        data_ref.random())
            End Function
        End Class

        Public Class jump_exportable_test
            Inherits exportable_test(Of [jump])

            Protected Overrides Function create() As [jump]
                Return New [jump]( _
                        data_ref.random())
            End Function
        End Class

        Public Class add_exportable_test
            Inherits exportable_test(Of [add])

            Protected Overrides Function create() As [add]
                Return New [add]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class sub_exportable_test
            Inherits exportable_test(Of [sub])

            Protected Overrides Function create() As [sub]
                Return New [sub]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class movc_exportable_test
            Inherits exportable_test(Of [movc])

            Protected Overrides Function create() As [movc]
                Return New [movc]( _
                        data_ref.random(),
                        data_block.random())
            End Function
        End Class

        Public Class mov_exportable_test
            Inherits exportable_test(Of [mov])

            Protected Overrides Function create() As [mov]
                Return New [mov]( _
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class mul_exportable_test
            Inherits exportable_test(Of [mul])

            Protected Overrides Function create() As [mul]
                Return New [mul]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class div_exportable_test
            Inherits exportable_test(Of [div])

            Protected Overrides Function create() As [div]
                Return New [div]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class ext_exportable_test
            Inherits exportable_test(Of [ext])

            Protected Overrides Function create() As [ext]
                Return New [ext]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class pow_exportable_test
            Inherits exportable_test(Of [pow])

            Protected Overrides Function create() As [pow]
                Return New [pow]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class jumpif_exportable_test
            Inherits exportable_test(Of [jumpif])

            Protected Overrides Function create() As [jumpif]
                Return New [jumpif]( _
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class cpip_exportable_test
            Inherits exportable_test(Of [cpip])

            Protected Overrides Function create() As [cpip]
                Return New [cpip]( _
                        data_ref.random())
            End Function
        End Class

        Public Class cpco_exportable_test
            Inherits exportable_test(Of [cpco])

            Protected Overrides Function create() As [cpco]
                Return New [cpco]( _
                        data_ref.random())
            End Function
        End Class

        Public Class cpdbz_exportable_test
            Inherits exportable_test(Of [cpdbz])

            Protected Overrides Function create() As [cpdbz]
                Return New [cpdbz]( _
                        data_ref.random())
            End Function
        End Class

        Public Class cpin_exportable_test
            Inherits exportable_test(Of [cpin])

            Protected Overrides Function create() As [cpin]
                Return New [cpin]( _
                        data_ref.random())
            End Function
        End Class

        Public Class stop_exportable_test
            Inherits exportable_test(Of [stop])

            Protected Overrides Function create() As [stop]
                Return New [stop]()
            End Function
        End Class

        Public Class equal_exportable_test
            Inherits exportable_test(Of [equal])

            Protected Overrides Function create() As [equal]
                Return New [equal]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class less_exportable_test
            Inherits exportable_test(Of [less])

            Protected Overrides Function create() As [less]
                Return New [less]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class app_exportable_test
            Inherits exportable_test(Of [app])

            Protected Overrides Function create() As [app]
                Return New [app]( _
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class sapp_exportable_test
            Inherits exportable_test(Of [sapp])

            Protected Overrides Function create() As [sapp]
                Return New [sapp]( _
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class cut_exportable_test
            Inherits exportable_test(Of [cut])

            Protected Overrides Function create() As [cut]
                Return New [cut]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class cutl_exportable_test
            Inherits exportable_test(Of [cutl])

            Protected Overrides Function create() As [cutl]
                Return New [cutl]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class extern_exportable_test
            Inherits exportable_test(Of [extern])

            Protected Overrides Function create() As [extern]
                Return New [extern]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class clr_exportable_test
            Inherits exportable_test(Of [clr])

            Protected Overrides Function create() As [clr]
                Return New [clr]( _
                        data_ref.random())
            End Function
        End Class

        Public Class scut_exportable_test
            Inherits exportable_test(Of [scut])

            Protected Overrides Function create() As [scut]
                Return New [scut]( _
                        data_ref.random(),
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class sizeof_exportable_test
            Inherits exportable_test(Of [sizeof])

            Protected Overrides Function create() As [sizeof]
                Return New [sizeof]( _
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

        Public Class empty_exportable_test
            Inherits exportable_test(Of [empty])

            Protected Overrides Function create() As [empty]
                Return New [empty]( _
                        data_ref.random(),
                        data_ref.random())
            End Function
        End Class

    End Namespace
End Namespace
