
Option Explicit On
Option Infer Off
Option Strict On

'this file is generated by /osi/service/resource/zipgen/zipgen.exe with
'nlexer_rule syntaxer_rule
'so change /osi/service/resource/gen/gen.cs or resource files instead of this file

Imports System.IO
Imports System.IO.Compression
Imports osi.root.connector

Friend Module bstyle_rules
    Public ReadOnly nlexer_rule() As Byte
    Public ReadOnly syntaxer_rule() As Byte

    Sub New()
        nlexer_rule = Convert.FromBase64String(strcat_hint(CUInt(108), _
        "H4sIAAAAAAAEAHu/ez8vl6efs0+oi6uCnp5+cUZiUWqKfl5OakVqUXxRaU6qXklFCS8XL1dRalpqUWpecqqCGoiLV48RTBMAfAhv7l8AAAA="))

        assert(nlexer_rule.ungzip(nlexer_rule))
        syntaxer_rule = Convert.FromBase64String(strcat_hint(CUInt(388), _
        "H4sIAAAAAAAEAHVRzU7DMAy+R8o75Iya7RE4AAckxI1TNSG3ddtoWVw5DtvenpRsZdXgFPuzv58kWr2+P719PL+YzWYbR2DstvEcBE7In5w8buQkWmnFcLQBDmiPTkbbkZgrYnKj1U9V323tHpY9reQ8YaH8Ykwkdh6YBiLapdUqYhAM7UUr4sHZljyFsvjfVKue2HqiyeyPNtcmCrDYhqHdo5j6C3xC22HvghNHoTJXpPXAMEO7R3NjVxh/YTYzUsTKuCEQ5/AYkxfbp9DOMrYF7zMPQ7fYT9liYJhGrYrEHJ/STb4Vew7HDhpf3i075VsPyJVp3JByU5nUe4J8NkR5PQq7MOzKf624prz3GqtHhOkifcfIKt9L9dOwHwIAAA=="))

        assert(syntaxer_rule.ungzip(syntaxer_rule))
    End Sub
End Module
