
Option Explicit On
Option Infer Off
Option Strict On

'this file is generated by /osi/service/resource/zipgen/zipgen.exe with
'nlexer_rule syntaxer_rule
'so change /osi/service/resource/gen/gen.cs or resource files instead of this file

Imports System.IO
Imports System.IO.Compression
Imports osi.root.connector

Friend Module bstyle_rules
    Public ReadOnly nlexer_rule() As Byte
    Public ReadOnly syntaxer_rule() As Byte

    Sub New()
        nlexer_rule = Convert.FromBase64String(strcat_hint(CUInt(108), _
        "H4sIAAAAAAAEAHu/ez8vl6efs0+oi6uCnp5+cUZiUWqKfl5OakVqUXxRaU6qXklFCS8XL1dRalpqUWpecqqCGoiLV48RTBMAfAhv7l8AAAA="))

        assert(nlexer_rule.ungzip(nlexer_rule))
        syntaxer_rule = Convert.FromBase64String(strcat_hint(CUInt(480), _
        "H4sIAAAAAAAEAH1SQW7DIBC8I/EHzpVJntBD20OlqreeLKvCeG2jULCWpU5+X2zHThOinIBhZneGhbP3z5ePr9c3sdvtQ68Qmn04OVJHwG+MFnZ0JM44QzVKp35AjoZ62XgSKyLSgbN5V2as6mnjcUanARbJBUPvSU4Xomyj02S8K8SvshFkA61xZkKWcgF+jNTeTowe1JAI2ipU9xlrjQcU47SNDRRi7pRW07q0lSOqYYCmENZ3Rue6ye7Mu70IhFFTxVkAR+A03FJEaTrnESRCiJbkGllqZW2eO895J9cKJSCGFAKBIrrteBhljaAO5zSb++pZXHxx1nqU1vth4qd9iqKQklLpA5Aoc2eZj6uCZ8U9bHP24CmSDlyztR9Siy4NpedsKTE9q4///GUPiUbVdvlt06AJOsBC1KaL6VCI2Fqv0lp7b+e5GddVyy+/0orll15j5TyVpXSmSFX+AJ4YqdtVAwAA"))

        assert(syntaxer_rule.ungzip(syntaxer_rule))
    End Sub
End Module
