<Project>
  <PropertyGroup>
    <RootProps>true</RootProps>
    <RootPath Condition="!Exists('$(RootPath)\root.net8.props')">$(MSBuildThisFileDirectory)</RootPath>
    <ServicePath>$(RootPath)..\service\</ServicePath>
    <ProductionPath>$(RootPath)..\production\</ProductionPath>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(RootPath)constants\constants.net8.vbproj" />
    <ProjectReference Include="$(RootPath)template\template.net8.vbproj" />
    <ProjectReference Include="$(RootPath)delegates\delegates.net8.vbproj" />
    <ProjectReference Include="$(RootPath)connector\connector.net8.vbproj" />
    <ProjectReference Include="$(RootPath)envs\envs.net8.vbproj" />
    <ProjectReference Include="$(RootPath)lock\lock.net8.vbproj" />
    <ProjectReference Include="$(RootPath)event\event.net8.vbproj" />
    <ProjectReference Include="$(RootPath)formation\formation.net8.vbproj" />
    <ProjectReference Include="$(RootPath)threadpool\threadpool.net8.vbproj" />
    <ProjectReference Include="$(RootPath)procedure\procedure.net8.vbproj" />
    <ProjectReference Include="$(RootPath)utils\utils.net8.vbproj" />
  </ItemGroup>
</Project>
