
Option Explicit On
Option Infer Off
Option Strict On

'this file is generated by /osi/service/resource/gen/gen.exe with
'case1 case2
'so change /osi/service/resource/gen/gen.cs or resource files instead of this file

Imports osi.root.connector

Friend Module _bstyle_test_data
    Public ReadOnly case1() As Byte
    Public ReadOnly case2() As Byte

    Sub New()
        case1 = Convert.FromBase64String(strcat_hint(CUInt(172), _
        "77u/DQp2b2lkIHByaW50KHN0cmluZyBpKSB7DQogIHN0cmluZyB0ZW1wOw0KICBsb2dpYyAiaW50ZXJydXB0IHN0ZG91dCBpIHRlbXAiOw0KfQ0KDQp2b2lkIG1haW4oKSB7DQogIHByaW50KCJIZWxsbyBXb3JsZCIpOw0KfQ=="))
        case2 = Convert.FromBase64String(strcat_hint(CUInt(884), _
        "77u/DQpib29sIGVxdWFsKGludCBpLCBpbnQgaikgew0KICBib29sIHJlc3VsdDsNCiAgbG9naWMgImVxdWFsIHJlc3VsdCBpIGoiOw0KICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpib29sIGlzX2V2ZW4oaW50IGkpIHsNCiAgaW50IHF1b3RpZW50Ow0KICBpbnQgcmVtYWluZGVyOw0KICBpbnQgdiA9IDI7DQogIGxvZ2ljICJkaXZpZGUgcXVvdGllbnQgcmVtYWluZGVyIGkgdiI7DQogIHJldHVybiBlcXVhbChyZW1haW5kZXIsIDApOw0KfQ0KDQp2b2lkIHByaW50KGJvb2wgaSkgew0KICBzdHJpbmcgdGVtcDsNCiAgbG9naWMgImludGVycnVwdCBzdGRvdXQgaSB0ZW1wIjsNCn0NCg0KaW50IGN1cnJlbnRfbXMoKSB7DQogIGludCByZXN1bHQ7DQogIGludCB0ZW1wOw0KICBsb2dpYyAiaW50ZXJydXB0IGN1cnJlbnRfbXMgdGVtcCByZXN1bHQiOw0KICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQppbnQgc2VsZl9kZWNyZWFzZShpbnQgeCkgew0KICBpbnQgdGVtcCA9IDE7DQogIGxvZ2ljICJzdWJ0cmFjdCB4IHggdGVtcCI7DQogIHJldHVybiB4Ow0KfQ0KDQp2b2lkIG1haW4oKSB7DQogIGludCB4Ow0KICB4ID0gY3VycmVudF9tcygpOw0KICBpZiAoaXNfZXZlbnQoeCkpIHsNCiAgICB4ID0gc2VsZl9kZWNyZWFzZSh4KTsNCiAgfQ0KICBwcmludChpc19ldmVudCh4KSk7DQp9"))
    End Sub
End Module
