<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>osi.production.sider</RootNamespace>
    <AssemblyName>osi.production.sider</AssemblyName>
    <OptionExplicit>On</OptionExplicit>
    <OptionCompare>Binary</OptionCompare>
    <OptionStrict>Off</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System" />
  </ItemGroup>

  <Import Project="..\..\root\root.production.net8.props" />
  <Import Project="$(ServicePath)\storage\storage.net8.props" />
  <Import Project="$(ServicePath)\configuration\configuration.net8.props" />
  <Import Project="$(ServicePath)\argument\argument.net8.props" />
  <Import Project="$(ServicePath)\selector\selector.net8.props" />
  <Import Project="$(ServicePath)\http\http.net8.props" />
  <Import Project="$(ServicePath)\tcp\tcp.net8.props" />
  <Import Project="$(ServicePath)\zip\zip.net8.props" />
  <Import Project="$(ServicePath)\secure\secure.net8.props" />
</Project>
