
Option Explicit On
Option Infer Off
Option Strict On

'the following code is generated by /osi/root/codegen/precompile/precompile.exe
'with hashset.iterator.vbp ----------
'so change hashset.iterator.vbp instead of this file



'the following code is generated by /osi/root/codegen/precompile/precompile.exe
'with ..\..\codegen\iterator.imports.vbp ----------
'so change ..\..\codegen\iterator.imports.vbp instead of this file


Imports System.Runtime.CompilerServices
Imports osi.root.connector
Imports osi.root.constants
'finish ..\..\codegen\iterator.imports.vbp --------
Imports osi.root.template

Public Module _hashset_iterator

'the following code is generated by /osi/root/codegen/precompile/precompile.exe
'with ..\..\codegen\iterator.ext.vbp ----------
'so change ..\..\codegen\iterator.ext.vbp instead of this file


    <Extension()> Public Function null_or_end(Of T, _UNIQUE As _boolean, _HASHER As _to_uint32(Of T), _EQUALER As _equaler(Of T))(ByVal this As hashset(Of T, _UNIQUE, _HASHER, _EQUALER).iterator) As Boolean
        Return this.is_null() OrElse this.is_end()
    End Function
'finish ..\..\codegen\iterator.ext.vbp --------
End Module

Partial Public Class hashset(Of T,
                                _UNIQUE As _boolean,
                                _HASHER As _to_uint32(Of T),
                                _EQUALER As _equaler(Of T))
    Public Structure iterator

'the following code is generated by /osi/root/codegen/precompile/precompile.exe
'with ..\..\codegen\random_access_iterator.single_step.vbp ----------
'so change ..\..\codegen\random_access_iterator.single_step.vbp instead of this file



'the following code is generated by /osi/root/codegen/precompile/precompile.exe
'with ..\..\codegen\random_access_iterator.vbp ----------
'so change ..\..\codegen\random_access_iterator.vbp instead of this file



'the following code is generated by /osi/root/codegen/precompile/precompile.exe
'with ..\..\codegen\static_iterator.vbp ----------
'so change ..\..\codegen\static_iterator.vbp instead of this file



        Implements IComparable(Of iterator), IComparable

        Public Shared ReadOnly [end] As iterator

        Shared Sub New()
            [end] = New iterator()
        End Sub

        Private ReadOnly p As ref

#If False Then
        <MethodImpl(method_impl_options.aggressive_inlining)>
        Friend Sub New(ByVal that As ref)
#Else
        <MethodImpl(method_impl_options.aggressive_inlining)>
        Private Sub New(ByVal that As ref)
#End If
#If Not False Then
            assert(Not that Is Nothing)
#End If
            p = that
        End Sub

#If False Then
        <MethodImpl(method_impl_options.aggressive_inlining)>
        Public Function is_end() As Boolean
            Return p.is_end()
        End Function
#Else
        <MethodImpl(method_impl_options.aggressive_inlining)>
        Public Function is_end() As Boolean
#If False Then
            Return p Is Nothing
#Else
            Return p Is Nothing AndAlso
                   assert(object_compare(Me, [end]) = 0)
#End If
        End Function
#End If

        <MethodImpl(method_impl_options.aggressive_inlining)>
        Public Function is_not_end() As Boolean
            Return Not is_end()
        End Function

#If False Then
        Private Shared Function is_equal(ByVal this As ref, ByVal that As ref) As Boolean
            Return object_compare(this, that) = 0
        End Function
#End If

        <MethodImpl(method_impl_options.aggressive_inlining)>
        Public Shared Operator =(ByVal this As iterator, ByVal that As iterator) As Boolean
            If this.null_or_end() AndAlso that.null_or_end() Then
                Return True
            End If
            If this.null_or_end() OrElse that.null_or_end() Then
                Return False
            End If
            assert(Not this.is_null() AndAlso Not this.is_null())
            Return is_equal(this.p, that.p)
        End Operator

        <MethodImpl(method_impl_options.aggressive_inlining)>
        Public Shared Operator <>(ByVal this As iterator, ByVal that As iterator) As Boolean
            Return Not (this = that)
        End Operator

        <MethodImpl(method_impl_options.aggressive_inlining)>
        Public Function CompareTo(ByVal other As iterator) As Int32 Implements IComparable(Of iterator).CompareTo
            Return If(Me = other, 0, -1)
        End Function

        <MethodImpl(method_impl_options.aggressive_inlining)>
        Public Function CompareTo(ByVal other As Object) As Int32 Implements IComparable.CompareTo
            Return CompareTo(cast(Of iterator)(other, False))
        End Function

    #If False Then
        <MethodImpl(method_impl_options.aggressive_inlining)>
        Public Shared Operator +(ByVal this As iterator) As ref
            Return If(this = [end], Nothing, this.p)
        End Operator
    #End If
'finish ..\..\codegen\static_iterator.vbp --------

        '1. iterator / reverse_iterator are combined together
        '2. do not allow to - from end, it's not must-have
        '3. operator+ / operator- should not impact current instance, considering i = j + 1
        <MethodImpl(method_impl_options.aggressive_inlining)>
        Public Shared Operator +(ByVal this As iterator, ByVal that As Int32) As iterator
            If this.null_or_end() OrElse that = 0 Then
                Return this
            End If
            If that > 0 Then
                Return this.move_next(CUInt(that))
            End If
            assert(that < 0)
            Return this.move_prev(CUInt(-that))
        End Operator

        Public Shared Operator -(ByVal this As iterator, ByVal that As Int32) As iterator
            Return this + (-that)
        End Operator
'finish ..\..\codegen\random_access_iterator.vbp --------

        Private Function move_next(ByVal i As UInt32) As iterator
            assert(i > uint32_0)
            Dim n As iterator = Nothing
            n = Me
            While Not n.is_end() AndAlso i > uint32_0
                n = n.move_next()
                i -= uint32_1
            End While
            Return n
        End Function

        Private Function move_prev(ByVal i As UInt32) As iterator
            assert(i > uint32_0)
            Dim n As iterator = Nothing
            n = Me
            While Not n.is_end() AndAlso i > uint32_0
                n = n.move_prev()
                i -= uint32_1
            End While
            Return n
        End Function
'finish ..\..\codegen\random_access_iterator.single_step.vbp --------

        Friend Sub New(ByVal owner As hashset(Of T, _UNIQUE, _HASHER, _EQUALER),
                       ByVal row As UInt32,
                       ByVal column As [set](Of T).iterator)
            Me.New(assert_not_nothing_return(owner).ref_at(row, column))
        End Sub

        Private Function move_next() As iterator
            Dim row As UInt32 = 0
            Dim column As [set](Of T).iterator = Nothing
            row = p.row
            column = p.column + 1
            While column.is_end() AndAlso row < p.last_row()
                row += uint32_1
                column = p.row_set(row).begin()
            End While
            If column.is_end() Then
                Return [end]
            End If
            Return New iterator(p.ref_at(row, column))
        End Function

        Private Function move_prev() As iterator
            Dim row As UInt32 = 0
            Dim column As [set](Of T).iterator = Nothing
            row = p.row
            column = p.column - 1
            While column.is_end() AndAlso row > uint32_0
                row -= uint32_1
                column = p.row_set(row).rbegin()
            End While
            If column.is_end() Then
                Return [end]
            End If
            Return New iterator(p.ref_at(row, column))
        End Function

        Private Shared Function is_equal(ByVal this As ref, ByVal that As ref) As Boolean
            assert(Not this Is Nothing AndAlso Not that Is Nothing)
            Return this.is_equal_to(that)
        End Function

        Friend Function ref() As ref
            Return p
        End Function

        Public Function value() As T
            Return +p
        End Function

        Public Shared Operator +(ByVal this As iterator) As T
            Return If(this = [end], Nothing, this.value())
        End Operator
    End Structure
End Class
'finish hashset.iterator.vbp --------
