<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net8.0-windows'">
    <ResourceProps>true</ResourceProps>
  </PropertyGroup>
  <Import Project="resource.net8.dep" Condition="'$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net8.0-windows'" />
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net8.0-windows'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)resource.net8.vbproj" />
  </ItemGroup>
</Project>
