<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net8.0-windows'">
    <ArgumentProps>true</ArgumentProps>
  </PropertyGroup>
  <Import Project="argument.net8.dep" Condition="'$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net8.0-windows'" />
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net8.0-windows'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)argument.net8.vbproj" />
  </ItemGroup>
</Project>
