
Option Explicit On
Option Infer Off
Option Strict On

'the following code is generated by /osi/root/codegen/precompile/precompile.exe
'with resolver.vbp ----------
'so change resolver.vbp instead of this file



Imports osi.root.connector
Imports osi.root.constants

Public NotInheritable Class resolver(Of T As Class)
#If False Then
    Private ReadOnly l As Object
#End If
    Private f As Func(Of T)
    Private cached As T

#If False Then
    Public Sub New()
        l = New Object()
    End Sub
#End If

    Public Sub register(ByVal i As T)
#If False Then
        SyncLock l
#End If
        cached = i
#If False Then
        End SyncLock
#End If
    End Sub

    Public Sub unregister()
        register([default](Of Func(Of T)).null)
    End Sub

    Public Sub register(ByVal i As Func(Of T))
#If False Then
        SyncLock l
#End If
        f = i
        cached = Nothing
#If False Then
        End SyncLock
#End If
    End Sub

    Public Function resolve(ByRef o As T) As Boolean
        If cached Is Nothing Then
#If False Then
            SyncLock l
#End If
            If cached Is Nothing Then
                If f Is Nothing Then
                    Return False
                End If
                cached = f()
            End If
#If False Then
            End SyncLock
#End If
        End If
        assert(Not cached Is Nothing)
        o = cached
        Return True
    End Function
End Class
'finish resolver.vbp --------
